export const LOAD_TWEETS_BY_KEY = 'LOAD_TWEETS_BY_KEY';
export const LOAD_TWEETS_BY_KEY_SUCCESS = 'LOAD_TWEETS_BY_KEY_SUCCESS';
export const LOAD_TWEETS_BY_KEY_ERROR = 'LOAD_TWEETS_BY_KEY_ERROR';

export const LOAD_USER_TWEETS = 'LOAD_USER_TWEETS';
export const LOAD_USER_TWEETS_SUCCES = 'LOAD_USER_TWEETS_SUCCES';
export const LOAD_USER_TWEETS_ERROR = 'LOAD_USER_TWEETS_ERROR';